site_name: Test material
site_url: https://tapeline.github.io/mkdocs-material2014
repo_url: https://github.com/Tapeline/material1-doc
copyright: "&copy; Copyright Tapeline 2025"
nav:
  - Home: index.md
  - Getting started:
      - Installing: get_started/install.md
      - Create docs: get_started/create.md
      - Publish docs: get_started/publish.md
  - Usage:
      - Configuration: usage/configuration.md
      - Syntax: usage/syntax.md
  - Demo:
      - Demo page: test/test.md
      - Admonitions: test/admonitions.md
      - Code: test/code.md
      - Content tabs: test/content-tabs.md
      - Diagrams: test/diagrams.md
      - Footnotes: test/footnotes.md
      - Formatting: test/formatting.md
      - Task list: test/tasklist.md
      - Term list: test/termlist.md

theme:
  name: material2014
  primary_color: "#E91E63"
  section_color:
    Getting started: "#009688"
    Usage: "#9C27B0"
    Demo: "#3F51B5"

plugins:
  - mermaid2
  - ezglossary
  - search

markdown_extensions:
  - toc:
      toc_depth: 3
  - extra
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - attr_list
  - md_in_html
  - def_list
  - material2014.extensions.tabbed
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
