site_name: MkDocs Material 2014
dev_addr: 127.0.0.1:8000
site_url: https://tapeline.github.io/mkdocs-material2014
repo_url: https://github.com/Tapeline/mkdocs-material2014
copyright: "&copy; Copyright Tapeline 2025"
nav:
  - Home: index.md
  - Getting started:
      - Installing: get_started/install.md
      - Create docs: get_started/create.md
      - Publish docs: get_started/publish.md
  - Usage:
      - Configuration: usage/configuration.md
      - Syntax: usage/syntax.md
  - Demo:
      - Markdown demo page: demo/test.md
      - Components:
          - Admonitions: demo/admonitions.md
          - Code: demo/code.md
          - Content tabs: demo/content-tabs.md
          - Diagrams: demo/diagrams.md
          - Footnotes: demo/footnotes.md
          - Formatting: demo/formatting.md
          - Task list: demo/tasklist.md
          - Term list: demo/termlist.md
          - OpenAPI: demo/openapi.md
theme:
  name: material2014
  primary_color: "#E91E63"
  section_color:
    Getting started: "#009688"
    Usage: "#9C27B0"
    Demo: "#3F51B5"
  footer_links:
    Debug page: /mkdocs-material2014/debug
    Testing: /mkdocs-material2014/test/home
  syntax_scheme: material

plugins:
  - macros:
      module_name: macros
  - mermaid2
  - ezglossary:
      tooltip: full
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

markdown_extensions:
  - toc:
      toc_depth: 3
  - extra
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - attr_list
  - md_in_html
  - def_list
  - material2014.extensions.tabbed
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
