site_name: MkDocs Material 2014
dev_addr: 127.0.0.1:8000
site_url: https://tapeline.github.io/mkdocs-material2014
repo_url: https://github.com/Tapeline/mkdocs-material2014
copyright: "&copy; Copyright Tapeline 2025"
nav:
  - Home: index.md
  - Getting started:
      - Installing: get_started/install.md
      - Create docs: get_started/create.md
      - Publish docs: get_started/publish.md
  - Usage:
      - Configuration: usage/configuration.md
      - Syntax: usage/syntax.md
  - Demo:
      - Markdown demo page: test/test.md
      - Admonitions: test/admonitions.md
      - Code: test/code.md
      - Content tabs: test/content-tabs.md
      - Diagrams: test/diagrams.md
      - Footnotes: test/footnotes.md
      - Formatting: test/formatting.md
      - Task list: test/tasklist.md
      - Term list: test/termlist.md
  - A very rich section:
      - This section:
          - Demonstrates: ""
          - How 3-item deep menu: ""
          - Will look like: ""
      - Isn't it:
          - Cool?: ""
theme:
  name: material2014
  primary_color: "#E91E63"
  section_color:
    Getting started: "#009688"
    Usage: "#9C27B0"
    Demo: "#3F51B5"
  footer_links:
    Debug page: /mkdocs-material2014/debug

plugins:
  - mermaid2
  - ezglossary:
      tooltip: full
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

markdown_extensions:
  - toc:
      toc_depth: 3
  - extra
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - attr_list
  - md_in_html
  - def_list
  - material2014.extensions.tabbed
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
